export default {
  GET_CONTENT_UNIT_LIST: 'global/GET_CONTENT_UNIT_LIST',
  ADD_CONTENT_UNIT: 'global/ADD_CONTENT_UNIT',
  RESORT_CONTENT: 'global/RESORT_CONTENT',  
  CREATE_UNIT: 'global/CREATE_UNIT'
}
